"""Indian identity number validators.  OWNER: Harin

Format regexes alone produce false positives: any 12-digit string looks like an
Aadhaar. Real checksum validation is what makes detection defensible, and it is
worth being able to explain to the jury.

No real identity numbers appear in this file or its tests. Valid samples are
generated by the checksum routines below.
"""

import re
from collections.abc import Callable

# Aadhaar uses the Verhoeff dihedral-group checksum, NOT Luhn. Verhoeff catches
# all single-digit errors and all adjacent transpositions, which Luhn does not;
# transposition is the dominant error when a 12-digit number is keyed by hand.
# The scheme is non-commutative, so the three tables below cannot be collapsed
# into arithmetic the way Luhn can.

# Multiplication table for the dihedral group D5.
_VERHOEFF_D = (
    (0, 1, 2, 3, 4, 5, 6, 7, 8, 9),
    (1, 2, 3, 4, 0, 6, 7, 8, 9, 5),
    (2, 3, 4, 0, 1, 7, 8, 9, 5, 6),
    (3, 4, 0, 1, 2, 8, 9, 5, 6, 7),
    (4, 0, 1, 2, 3, 9, 5, 6, 7, 8),
    (5, 9, 8, 7, 6, 0, 4, 3, 2, 1),
    (6, 5, 9, 8, 7, 1, 0, 4, 3, 2),
    (7, 6, 5, 9, 8, 2, 1, 0, 4, 3),
    (8, 7, 6, 5, 9, 3, 2, 1, 0, 4),
    (9, 8, 7, 6, 5, 4, 3, 2, 1, 0),
)

# Permutation table, applied cyclically by digit position.
_VERHOEFF_P = (
    (0, 1, 2, 3, 4, 5, 6, 7, 8, 9),
    (1, 5, 7, 6, 2, 8, 3, 0, 9, 4),
    (5, 8, 0, 3, 7, 9, 6, 1, 4, 2),
    (8, 9, 1, 6, 0, 4, 3, 5, 2, 7),
    (9, 4, 5, 3, 1, 2, 6, 8, 7, 0),
    (4, 2, 8, 6, 5, 7, 3, 9, 0, 1),
    (2, 7, 9, 3, 8, 0, 6, 4, 1, 5),
    (7, 0, 4, 6, 9, 1, 3, 2, 5, 8),
)

# Inverse table: the digit that cancels an intermediate value back to zero.
_VERHOEFF_INV = (0, 4, 3, 2, 1, 5, 6, 7, 8, 9)

_PAN_RE = re.compile(r"^[A-Z]{5}[0-9]{4}[A-Z]$")
_IFSC_RE = re.compile(r"^[A-Z]{4}0[A-Z0-9]{6}$")
_PASSPORT_RE = re.compile(r"^[A-Z][0-9]{7}$")
_VOTER_ID_RE = re.compile(r"^[A-Z]{3}[0-9]{7}$")

# Base-36 alphabet for the GSTIN check character.
_GSTIN_CODEPOINTS = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ"

_GSTIN_MIN_STATE_CODE = 1
_GSTIN_MAX_STATE_CODE = 38


def _clean(value: str) -> str:
    """Strip the separators people type into forms, and uppercase."""
    if not isinstance(value, str):
        return ""
    return re.sub(r"[\s\-]", "", value).strip().upper()


def verhoeff_checksum(payload: str) -> int:
    """Return the Verhoeff check digit for a digit string without one.

    Exposed so tests and fixtures can build synthetic numbers instead of
    hardcoding any real identity number.
    """
    digits = _clean(payload)
    if not digits.isdigit():
        raise ValueError("verhoeff_checksum expects a string of digits")
    c = 0
    # Position 0 of the permutation table is reserved for the check digit
    # itself, so a payload digit at reverse index i uses row i + 1.
    for i, char in enumerate(reversed(digits)):
        c = _VERHOEFF_D[c][_VERHOEFF_P[(i + 1) % 8][int(char)]]
    return _VERHOEFF_INV[c]


def verhoeff_validate(value: str) -> bool:
    """True when a digit string carries its own valid Verhoeff check digit."""
    digits = _clean(value)
    if not digits.isdigit() or not digits:
        return False
    c = 0
    # The digits are consumed in reverse so that the check digit lands on
    # permutation row 0. Walking forward instead fails every valid number.
    for i, char in enumerate(reversed(digits)):
        c = _VERHOEFF_D[c][_VERHOEFF_P[i % 8][int(char)]]
    return c == 0


def is_valid_aadhaar(value: str) -> bool:
    """12 digits, first digit 2-9, Verhoeff checksum."""
    digits = _clean(value)
    if len(digits) != 12 or not digits.isdigit():
        return False
    # UIDAI never issues a number starting with 0 or 1, which keeps Aadhaar out
    # of the numbering space of ordinary sequential ids.
    if digits[0] in "01":
        return False
    return verhoeff_validate(digits)


def is_valid_pan(value: str) -> bool:
    """AAAAA9999A. Fourth char encodes holder type, fifth is a surname initial."""
    return bool(_PAN_RE.match(_clean(value)))


def gstin_check_char(first_fourteen: str) -> str:
    """Return the GSTIN check character for the first 14 characters.

    Exposed so synthetic GSTINs can be built rather than hardcoded.
    """
    body = _clean(first_fourteen)
    if len(body) != 14 or any(ch not in _GSTIN_CODEPOINTS for ch in body):
        raise ValueError("gstin_check_char expects 14 base-36 characters")
    modulus = len(_GSTIN_CODEPOINTS)
    factor = 2
    total = 0
    # Weights alternate 2 and 1 from the right, and each product is folded
    # base-36 rather than base-10, which is what separates this from Luhn.
    for char in reversed(body):
        product = factor * _GSTIN_CODEPOINTS.index(char)
        factor = 1 if factor == 2 else 2
        total += (product // modulus) + (product % modulus)
    return _GSTIN_CODEPOINTS[(modulus - (total % modulus)) % modulus]


def is_valid_gstin(value: str) -> bool:
    """2-digit state code + PAN + entity code + Z + checksum character."""
    candidate = _clean(value)
    if len(candidate) != 15 or any(ch not in _GSTIN_CODEPOINTS for ch in candidate):
        return False
    state_code = candidate[:2]
    if not state_code.isdigit():
        return False
    if not _GSTIN_MIN_STATE_CODE <= int(state_code) <= _GSTIN_MAX_STATE_CODE:
        return False
    if not is_valid_pan(candidate[2:12]):
        return False
    if not candidate[12].isalnum():
        return False
    # The 14th character is a fixed 'Z' placeholder in the current GSTIN format.
    if candidate[13] != "Z":
        return False
    return candidate[14] == gstin_check_char(candidate[:14])


def is_valid_ifsc(value: str) -> bool:
    """4 letters + 0 + 6 alphanumeric."""
    return bool(_IFSC_RE.match(_clean(value)))


def is_valid_passport(value: str) -> bool:
    """1 letter + 7 digits."""
    return bool(_PASSPORT_RE.match(_clean(value)))


def is_valid_voter_id(value: str) -> bool:
    """3 letters + 7 digits."""
    return bool(_VOTER_ID_RE.match(_clean(value)))


def is_valid_card_number(value: str) -> bool:
    """13-19 digits passing the Luhn checksum."""
    digits = _clean(value)
    if not digits.isdigit() or not 13 <= len(digits) <= 19:
        return False
    total = 0
    for i, char in enumerate(reversed(digits)):
        digit = int(char)
        if i % 2 == 1:
            digit *= 2
            if digit > 9:
                digit -= 9
        total += digit
    return total % 10 == 0


def luhn_check_digit(payload: str) -> int:
    """Luhn check digit for a payload without one, for building test cards."""
    digits = _clean(payload)
    if not digits.isdigit():
        raise ValueError("luhn_check_digit expects a string of digits")
    total = 0
    for i, char in enumerate(reversed(digits)):
        digit = int(char)
        # The payload is one position short of the final number, so the
        # doubling parity is the opposite of the validation loop.
        if i % 2 == 0:
            digit *= 2
            if digit > 9:
                digit -= 9
        total += digit
    return (10 - (total % 10)) % 10


# Category name -> validator, used by the classifier to confirm a literal.
# Order matters: the narrower formats are tried before the broad digit runs.
VALIDATORS: tuple[tuple[str, Callable[[str], bool]], ...] = (
    ("gstin", is_valid_gstin),
    ("aadhaar", is_valid_aadhaar),
    ("pan", is_valid_pan),
    ("voter_id", is_valid_voter_id),
    ("passport", is_valid_passport),
    ("financial", is_valid_ifsc),
    ("financial", is_valid_card_number),
)
