"""PII taxonomy.  OWNER: Harin

Category -> sensitivity tier -> the DPDP sections that category triggers.
Sensitivity drives finding severity, so getting these tiers right matters.

Tier values are the string values of models.enums.Sensitivity. They are written
out as literals rather than imported: app.models.__init__ pulls in the whole
SQLAlchemy layer, and the scanner must stay usable without a database.

Section ids follow the corpus format ("s.5", "s.8(5)") so a category can be
handed straight to retrieval without re-mapping.
"""

CRITICAL = "critical"
HIGH = "high"
MEDIUM = "medium"
LOW = "low"

# Every item of personal data triggers notice, consent and security safeguards.
# Category-specific sections are added on top of this baseline.
_BASELINE_SECTIONS = ("s.5", "s.6", "s.8(5)")


def _sections(*extra: str) -> list[str]:
    return [*_BASELINE_SECTIONS, *extra]


PII_TAXONOMY: dict[str, dict] = {
    "name": {
        "sensitivity": MEDIUM,
        "sections": _sections(),
        "aliases": (
            "name",
            "full_name",
            "fullname",
            "first_name",
            "firstname",
            "fname",
            "last_name",
            "lastname",
            "lname",
            "middle_name",
            "given_name",
            "family_name",
            "surname",
            "legal_name",
            "display_name",
            "username",
            "user_name",
            "customer_name",
            "applicant_name",
            "employee_name",
            "patient_name",
            "account_holder_name",
            "holder_name",
            "cardholder_name",
            "beneficiary_name",
            "nominee_name",
            "father_name",
            "mother_name",
            "spouse_name",
            "guardian_name",
            "maiden_name",
            "name_on_card",
            "name_as_per_aadhaar",
        ),
    },
    "email": {
        "sensitivity": MEDIUM,
        # Email is the statutory contact channel for breach intimation, so it
        # carries s.8(6) as well as the baseline.
        "sections": _sections("s.8(6)"),
        "aliases": (
            "email",
            "e_mail",
            "email_address",
            "email_id",
            "emailid",
            "mail",
            "mail_address",
            "mail_id",
            "user_email",
            "contact_email",
            "work_email",
            "personal_email",
            "primary_email",
            "secondary_email",
            "alternate_email",
            "recovery_email",
            "billing_email",
            "login_email",
            "sender_email",
            "recipient_email",
            "smtp_user",
        ),
    },
    "phone": {
        # Indian mobile numbers are the OTP factor for most account recovery and
        # for Aadhaar eKYC, so exposure is an account-takeover path, not just a
        # contact leak. That is why this sits above name and email.
        "sensitivity": HIGH,
        "sections": _sections("s.8(6)"),
        "aliases": (
            "phone",
            "phone_number",
            "phone_no",
            "phoneno",
            "phone_num",
            "mobile",
            "mobile_number",
            "mobile_no",
            "mobileno",
            "mob_no",
            "msisdn",
            "contact_number",
            "contact_no",
            "contact_phone",
            "telephone",
            "telephone_number",
            "tel_no",
            "landline",
            "whatsapp_number",
            "alternate_number",
            "emergency_contact",
            "emergency_contact_number",
            "otp_mobile",
        ),
    },
    "aadhaar": {
        "sensitivity": CRITICAL,
        # Identity documents also engage s.8(1) accuracy and s.8(7) erasure, and
        # at volume they are the classic trigger for the s.10(2) assessment.
        "sections": _sections("s.8(1)", "s.8(7)", "s.10(2)"),
        "aliases": (
            "aadhaar",
            "aadhar",
            "adhaar",
            "adhar",
            "aadhaar_number",
            "aadhar_number",
            "aadhaar_no",
            "aadhar_no",
            "aadhaar_id",
            "uidai",
            "uidai_number",
            "uid_number",
            "aadhaar_uid",
            "vid",
            "virtual_id",
            "ekyc_number",
            "aadhaar_last_four",
        ),
    },
    "pan": {
        "sensitivity": CRITICAL,
        "sections": _sections("s.8(1)", "s.8(7)", "s.10(2)"),
        "aliases": (
            "pan",
            "pan_number",
            "pan_no",
            "pan_card",
            "pan_card_number",
            "pan_id",
            "permanent_account_number",
            "income_tax_pan",
            "tax_id",
            "tan",
            "tan_number",
        ),
    },
    "passport": {
        "sensitivity": CRITICAL,
        "sections": _sections("s.8(1)", "s.8(7)", "s.10(2)"),
        "aliases": (
            "passport",
            "passport_number",
            "passport_no",
            "passport_id",
            "passport_num",
            "travel_document",
            "travel_document_number",
        ),
    },
    "voter_id": {
        "sensitivity": HIGH,
        "sections": _sections("s.8(1)", "s.8(7)"),
        "aliases": (
            "voter_id",
            "voterid",
            "voter_id_number",
            "voter_card",
            "voter_card_number",
            "epic",
            "epic_number",
            "epic_no",
            "electoral_id",
            "election_card",
        ),
    },
    "gstin": {
        # GSTIN is a business registration number, but it embeds the holder PAN,
        # so it is personal data for a proprietor and is treated above baseline.
        "sensitivity": HIGH,
        "sections": _sections("s.8(1)", "s.8(7)"),
        "aliases": (
            "gstin",
            "gst_in",
            "gst",
            "gst_number",
            "gst_no",
            "gstin_number",
            "gst_identification_number",
            "gst_registration_number",
        ),
    },
    "dob": {
        "sensitivity": HIGH,
        # Date of birth is how age is determined, which is what puts a record
        # inside or outside the s.9 children regime.
        "sections": _sections("s.9"),
        "aliases": (
            "dob",
            "date_of_birth",
            "birth_date",
            "birthdate",
            "birthday",
            "born_on",
            "date_of_birth_str",
            "age",
            "age_years",
            "year_of_birth",
            "birth_year",
            "yob",
        ),
    },
    "address": {
        "sensitivity": HIGH,
        "sections": _sections("s.8(7)"),
        "aliases": (
            "address",
            "addr",
            "address_line",
            "address_line_1",
            "address_line_2",
            "address_line1",
            "address_line2",
            "addr_line_1",
            "addr_line_2",
            "street",
            "street_address",
            "house_number",
            "house_no",
            "flat_no",
            "building",
            "locality",
            "landmark",
            "area",
            "village",
            "taluka",
            "tehsil",
            "district",
            "city",
            "town",
            "state",
            "pincode",
            "pin_code",
            "postal_code",
            "postcode",
            "zip",
            "zipcode",
            "zip_code",
            "residential_address",
            "permanent_address",
            "current_address",
            "billing_address",
            "shipping_address",
            "delivery_address",
            "home_address",
            "office_address",
            "correspondence_address",
            "geo_location",
            "geolocation",
            "latitude",
            "longitude",
            "lat_long",
        ),
    },
    "ip_address": {
        "sensitivity": LOW,
        "sections": _sections(),
        "aliases": (
            "ip",
            "ip_address",
            "ipaddress",
            "ip_addr",
            "client_ip",
            "remote_ip",
            "remote_addr",
            "user_ip",
            "source_ip",
            "src_ip",
            "peer_ip",
            "x_forwarded_for",
            "device_id",
            "device_identifier",
            "mac_address",
            "imei",
            "advertising_id",
            "user_agent",
            "session_ip",
        ),
    },
    "financial": {
        "sensitivity": CRITICAL,
        "sections": _sections("s.8(6)", "s.8(7)", "s.10(2)"),
        "aliases": (
            "card_number",
            "cardnumber",
            "card_no",
            "credit_card",
            "credit_card_number",
            "debit_card",
            "debit_card_number",
            "cc_number",
            "ccnum",
            "cvv",
            "cvc",
            "card_cvv",
            "card_expiry",
            "expiry_date",
            "account_number",
            "acct_number",
            "account_no",
            "bank_account",
            "bank_account_number",
            "ifsc",
            "ifsc_code",
            "micr",
            "micr_code",
            "swift_code",
            "iban",
            "upi_id",
            "upi_handle",
            "vpa",
            "salary",
            "annual_income",
            "income",
            "net_worth",
            "credit_score",
            "cibil_score",
            "transaction_amount",
            "wallet_balance",
        ),
    },
    # face_template is deliberately absent: the generic "template" filter is
    # worth more than that one alias, and face_embedding covers the same column.
    "biometric": {
        "sensitivity": CRITICAL,
        "sections": _sections("s.8(1)", "s.8(7)", "s.10(2)"),
        "aliases": (
            "biometric",
            "biometric_data",
            "biometrics",
            "fingerprint",
            "finger_print",
            "fingerprint_hash",
            "thumb_impression",
            "iris",
            "iris_scan",
            "retina_scan",
            "face_id",
            "face_encoding",
            "face_embedding",
            "facial_data",
            "voice_print",
            "voiceprint",
            "gait_data",
            "palm_print",
            "dna",
            "dna_sequence",
        ),
    },
    "health": {
        "sensitivity": CRITICAL,
        "sections": _sections("s.8(7)", "s.10(2)"),
        "aliases": (
            "health",
            "health_data",
            "health_record",
            "medical_record",
            "medical_history",
            "medical_report",
            "diagnosis",
            "prescription",
            "treatment",
            "medication",
            "blood_group",
            "blood_type",
            "allergy",
            "allergies",
            "disability",
            "disability_status",
            "abha_id",
            "abha_number",
            "health_id",
            "insurance_policy_number",
            "patient_id",
            "mental_health",
            "pregnancy_status",
            "hiv_status",
            "vaccination_record",
        ),
    },
    "password": {
        "sensitivity": CRITICAL,
        "sections": _sections("s.8(6)"),
        "aliases": (
            "password",
            "passwd",
            "pwd",
            "pass_word",
            "password_hash",
            "hashed_password",
            "password_digest",
            "encrypted_password",
            "old_password",
            "new_password",
            "confirm_password",
            "current_password",
            "passphrase",
            "pin",
            "mpin",
            "security_answer",
            "secret_answer",
            "otp",
            "one_time_password",
            "otp_code",
            "reset_token",
            "session_token",
            "refresh_token",
            "access_token",
            "api_key",
            "api_secret",
            "secret_key",
            "private_key",
        ),
    },
}


# Substrings that mean a field only talks ABOUT personal data instead of holding
# any. Without these the scanner reports every UI label, validation regex and
# ORM metadata attribute, and the scorecard drowns in noise. Entries are matched
# as whole token runs, so "file_name" does not swallow "profile_name".
NEGATIVE_FILTERS: tuple[str, ...] = (
    # the canonical cases: a field that describes or renders personal data
    "email_template",
    "phone_format",
    "name_label",
    "address_placeholder",
    "email_regex",
    "name_format",
    "address_format",
    "email_placeholder",
    "phone_placeholder",
    "name_placeholder",
    "email_validation",
    "phone_validation",
    "aadhaar_regex",
    "pan_regex",
    # generic UI and copy
    "label",
    "labels",
    "placeholder",
    "caption",
    "heading",
    "title",
    "tooltip",
    "hint",
    "hint_text",
    "help_text",
    "helper_text",
    "error_text",
    "error_message",
    "success_message",
    "message_body",
    "prompt",
    "description",
    "subtitle",
    "legend",
    "aria_label",
    "alt_text",
    "button_text",
    "link_text",
    "display_text",
    "translation",
    "translations",
    "locale",
    "i18n",
    "l10n",
    # templating and rendering
    "template",
    "templates",
    "template_id",
    "template_name",
    "partial",
    "layout",
    "component",
    "widget",
    "markup",
    "html_body",
    "email_body",
    "email_subject",
    "subject_line",
    # validation and formatting
    "regex",
    "regexp",
    "pattern",
    "patterns",
    "format",
    "formats",
    "formatter",
    "validator",
    "validators",
    "validation",
    "validation_rule",
    "input_mask",
    "mask_pattern",
    "matcher",
    "min_length",
    "max_length",
    "length",
    "text_encoding",
    "file_encoding",
    "charset",
    "mime_type",
    "content_type",
    # test and demo data
    "example",
    "examples",
    "sample",
    "samples",
    "dummy",
    "mock",
    "stub",
    "fake",
    "faker",
    "factory",
    "fixture",
    "fixtures",
    "seed",
    "seeder",
    "test",
    "tests",
    "testing",
    "demo",
    "lorem",
    "placeholder_value",
    "test_id",
    "test_data",
    # configuration and schema metadata
    "config",
    "configuration",
    "settings",
    "setting",
    "option",
    "options",
    "choices",
    "enum",
    "constant",
    "constants",
    "default",
    "defaults",
    "schema",
    "schema_name",
    "spec",
    "openapi",
    "swagger",
    "docs",
    "doc_string",
    "docstring",
    "comment",
    # identifiers that name code or infrastructure, not people
    "column_name",
    "table_name",
    "class_name",
    "field_name",
    "file_name",
    "filename",
    "func_name",
    "function_name",
    "method_name",
    "variable_name",
    "var_name",
    "model_name",
    "module_name",
    "package_name",
    "db_name",
    "database_name",
    "app_name",
    "service_name",
    "host_name",
    "hostname",
    "domain_name",
    "bucket_name",
    "queue_name",
    "topic_name",
    "index_name",
    "key_name",
    "param_name",
    "parameter_name",
    "arg_name",
    "argument_name",
    "tag_name",
    "event_name",
    "job_name",
    "task_name",
    "route_name",
    "path_name",
    "env_name",
    "environment_name",
    "branch_name",
    "repo_name",
    "project_name",
    "plugin_name",
    "theme_name",
    "icon_name",
    "font_name",
    "color_name",
    "style_name",
    "attribute_name",
    "property_name",
    "node_name",
    "element_name",
    "command_name",
    "rule_name",
    "policy_name",
    "role_name",
    "group_name",
    "permission_name",
    "step_name",
    "stage_name",
    "brand_name",
    "product_name",
    "company_name",
    "org_name",
    "organisation_name",
    "organization_name",
    "team_name",
    "store_name",
    "vendor_name",
    "sender_name",
    "header_name",
    "cookie_name",
    "metric_name",
    "logger_name",
    # styling and selectors
    "css",
    "css_class",
    "class_list",
    "selector",
    "xpath",
    "style_sheet",
    "svg_path",
    # type, shape and counters rather than values. These are spelled out per
    # field instead of filtering a bare "type" token, which would also reject
    # real categories such as blood_type.
    "email_type",
    "phone_type",
    "address_type",
    "card_type",
    "id_type",
    "document_type",
    "data_type",
    "field_type",
    "input_type",
    "column_type",
    "file_type",
    "account_type",
    "user_type",
    "entity_type",
    "media_type",
    "node_type",
    "event_type",
    "notification_type",
    "kind",
    "category",
    "column_header",
    "table_header",
    "header",
    "headers",
    "count",
    "counter",
    "total",
    "index",
    "offset",
    "limit",
    "sort_order",
    "is_required",
    "is_visible",
    "is_hidden",
    "is_enabled",
    "is_disabled",
    "read_only",
    "editable",
)


def sensitivity_for(category: str) -> str:
    """Return the sensitivity tier for a PII category."""
    entry = PII_TAXONOMY.get(category)
    if entry is None:
        raise KeyError(f"unknown PII category: {category!r}")
    return entry["sensitivity"]


def sections_for(category: str) -> list[str]:
    """Return the DPDP sections a category implicates."""
    entry = PII_TAXONOMY.get(category)
    if entry is None:
        raise KeyError(f"unknown PII category: {category!r}")
    return list(entry["sections"])


def categories() -> list[str]:
    """Every category name the taxonomy knows about."""
    return list(PII_TAXONOMY)


def aliases_for(category: str) -> tuple[str, ...]:
    """Field-name aliases registered for a category."""
    entry = PII_TAXONOMY.get(category)
    if entry is None:
        raise KeyError(f"unknown PII category: {category!r}")
    return tuple(entry["aliases"])
